#define VDOWN_BUTTON 0 //矢印キー、十字キー
#define VLEFT_BUTTON 1
#define VRIGHT_BUTTON 2
#define VUP_BUTTON 3
#define DOWN_BUTTON 4//wasdのキー、アナログ
#define LEFT_BUTTON 5
#define RIGHT_BUTTON 6
#define UP_BUTTON 7
#define SQUARE_BUTTON 8
#define TRIANGLE_BUTTON 9
#define CROSS_BUTTON 10
#define CIRCLE_BUTTON 11
#define L1_BUTTON 12
#define R1_BUTTON 13
#define L2_BUTTON 14
#define R2_BUTTON 15
#define L3_BUTTON 16
#define R3_BUTTON 17
#define SELECT_BUTTON 18
#define PAUSE_BUTTON 19
